title: Valtellina-Valgerola 
author: nicolaGH-bit
email: your-email@domain.com
theme: minima
description: A beautiful valley.

# social links
twitter_username: dilenico
github_username: nicolaGH-bit

show_excerpts: true # set to false to remove excerpts on the homepage
