title: Collevalenza(PG) Italy
author: nicolaGH-bit
email: ndilembi@gmail.com
theme: minima
description: a holy place

twitter_username: dilenico
github_username:  nicolaGH-bit

show_excerpts: true # set to false to remove excerpts on the homepage
