title: Colombarone-Pesaro(Italy)
author: nicolaGH-bit
email: ndilembo@gmail.com
theme: minima

description: A beautiful place.

# social links
twitter_username: dilenico
github_username:  nicolaGH-bit

show_excerpts: true # set to false to remove excerpts on the homepage
